# Generated by Django 2.1.5 on 2021-11-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211126_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Select', on_delete=django.db.models.deletion.CASCADE, to='product.categorie'),
        ),
    ]
